# Replace the values inside the quote marks
API_KEY = ""
ANNOUNCE_URL = ""

# If using backslashes, ensure there are none at the end of the string.
# The input folder (or multiple folders) should be placed inside the brackets
INPUT_FOLDERS = ["C:\Media\Films", "D:\Media\Films"]

# The output folder should not be within brackets.
OUTPUT_FOLDER = "C:\Media"

# List of groups banned from being uploaded
BANNED_GROUPS = [""
    "3LTON",
    "4yEo",
    "ADE",
    "AFG",
    "AniHLS",
    "AnimeRG",
    "AniURL",
    "AROMA",
    "aXXo",
    "Brrip",
    "CHD",
    "CM8",
    "CrEwSaDe",
    "d3g",
    "DDR",
    "DNL",
    "DeadFish",
    "DNL",
    "ELiTE",
    "eSc",
    "FaNGDiNG0",
    "FGT",
    "Flights",
    "FRDS",
    "FUM",
    "HAiKU",
    "HD2DVD",
    "HDS",
    "HDTime",
    "Hi10",
    "ION10",
    "iPlanet",
    "JIVE",
    "KiNGDOM",
    "Leffe",
    "LiGaS",
    "LOAD",
    "MeGusta",
    "MkvCage",
    "mHD",
    "mSD",
    "NhaNc3",
    "nHD",
    "NOIVTC",
    "nSD",
    "Oj",
    "Ozlem",
    "PiRaTeS",
    "PRoDJi",
    "RAPiDCOWS",
    "RARBG",
    "RetroPeeps",
    "RDN",
    "REsuRRecTioN",
    "RMTeam",
    "SANTi",
    "SicFoI",
    "SPASM",
    "SPDVD",
    "STUTTERSHIT",
    "TBS",
    "Telly",
    "TM",
    "UPiNSMOKE",
    "URANiME",
    "WAF",
    "xRed",
    "XS",
    "YIFY",
    "YTS",
    "Zeus",
    "ZKBL",
    "ZmN",
    "ZMNT",
]
